dz-3
RatiboR1978/purpleschool_dz pull request #5
Opened 2024-03-17 10:49 UTC by RatiboR1978

Привет Алексей отправляю 3 дз

2024-03-17 19:57 UTC, GitEsense requested changes
10-array-clean - обратить внимание и переделать
11-date-array - доделать логику валидации даты (на данный момент отрабатывает некорректно)
12-luna - всё ок в целом, но запись можно сделать более "элегантной"

2024-03-17 19:57 UTC, GitEsense commented on 11-date-array/script.js
> +const arr = ["01.02.22", "11.12.23", "0.13.22", "41.12"]
//  Домашнее задание
/*
    Дан массив строк ['10-02-2022','тест','11/12/2023','00/13/2022','41/12/2023'];
    Необходимо написать функцию, которая удаляла бы из массива все строки, которые нельзя перевести в дату
    (можно: 10-02-2022 и 11/12/2023) и возвращала новый массив вида: 
    -   ['10-02-2022','12-11-2023']
*/

т.е. 
```js
const arr = ['10-02-2022','тест','11/12/2023','00/13/2022','41/12/2023'];
```

2024-03-17 19:57 UTC, GitEsense commented on 11-date-array/script.js
> +  return ((arr[0] > 0 && arr[0] < 32) && (arr[1] > 0 && arr[1] < 13)) ? true : false;
А если я в функцию передам скажем 30 февраля? - я получу валидную дату...
Нужна проверка каждой даты
на кол-во дней (сколько в каждом месяце)
на високосный год (тогда в феврале 29 дней, а не 28)

разные форматы входа
входная дата '12-03-2021' = 'RU' формат 12 марта 2021 года
входная дата '03\12\2021' = 'EN' формат 12 марта 2021 года

в данном случае при передаче EN формата - мы получим ошибку при парсинге месяца (ру формат дд.мм.гггг, а EN формат мм.дд.гггг)

Вот эту логику преобразования так же надо реализовать

2024-03-17 19:57 UTC, GitEsense commented on 10-array-clean/script.js
> +      result.push(arr[i]);
Вот тут Вы обращаетесь к функции numValidation, но зачем? если мы должны работать с функцией высшего порядка, иначе зачем мы тогда её передаём?
Скажем, а если я передам вторую функцию, которая удаляет всё что больше 5?
тогда я всё равно получу результат по функции numValidation

2024-03-17 19:57 UTC, GitEsense commented on 12-luna/script.js
> +}
```js
function cardLunaValidate(card) {
    const cardNumber = card
        .replaceAll('-', '')     //   убираем все "тире"
        .split('')     //   разбиваем на массив
        .map(Number);      //   преобразуем всё в число
    if (cardNumber.includes(NaN)) {
        return NaN;
    }
    const isEven = (cardNumber.length - 1) % 2 === 0;      //   Проверяем чётность массива

      //   Если массив чётный, начинаем со второго элемента
      //   Если массив не чётный, начинаем с первого элемента
      //   Сокращение итераций за счёт шага в 2 элемента (не нужно проходить по лишним элементам и каждый раз проверять чётность
    for (let i = isEven ? 1 : 0 ; i < cardNumber.length; i = i + 2) {
        cardNumber[i] =
            cardNumber[i] * 2 > 9 ? cardNumber[i] * 2 - 9 : cardNumber[i] * 2;
    }
    const sum = cardNumber.reduce((total, el) => total + el);
    return sum % 10 === 0;
}

const card = '234s834503458353';
const card1 = '2342834503458353';
const card2 = '4561-2612-1234-5464';
const card3 = '4561-2612-1534-5464';

function resultTemplate(card) {
    const startString = `Карта с номером: ${card}`;
    const endString = `получила результат: ${cardLunaValidate(card)}`;
    return `${startString} ${endString}`;
}
console.log(resultTemplate(card));
console.log(resultTemplate(card1));
console.log(resultTemplate(card2));
console.log(resultTemplate(card3));

2024-09-24 13:27 UTC, GitEsense approved these changes

2024-09-24 13:27 UTC, GitEsense commented on 11-date-array/script.js
> +console.log(transformDates(arr));
Очень странное решение передавать постоянно сепаратор, ведь мы по сути "не знаем какой нам придёт", тогда нужна логика "проверки", либо прогонять "все сепараторы" (тут лучше подойдёт regExp значение, но ладно...

оставлю для анализа решение, тут корректно разделяется дата по разделителю и реализована логика поведения в зависимости от разделителя

```js
const length = 30;

function randomNumber(min = 1, max = 35) {
    return Math.floor(Math.random() * (max - min + 1) + min)
}
const inputDates = Array.from({ length }, () => {
    const factor = Math.random() > 0.5 ? '/' : '-';

    const dateArray = [
        factor === '-' ? randomNumber() : randomNumber(0, 15),
        factor === '-' ? randomNumber(0, 15) : randomNumber(),
        randomNumber(1900, 2050),
    ].map((x) => x.toString().padStart(2, '0'));
    return dateArray.join(factor);
}).concat(Array.from({ length: 10 }, () => [randomNumber(28, 32), '02', randomNumber(1900, 2050)].join('-')));

function getDates(array, fn) {
    return array.map(stringToArray).filter(fn).sort(sortDatePattern).map(formatDate);
}

function formatDate(array) {
    return array.map(String).map((x, i) => (i === 2 ? x.padStart(4, '0') : x.padStart(2, '0'))).join('-');
}

function sortDatePattern(a, b) {
    let day, month, year;

    [day, month, year] = a;
    const dt1 = new Date(year, month - 1, day).getTime();

    [day, month, year] = b;
    const dt2 = new Date(year, month - 1, day).getTime();

    return dt1 - dt2;
}

function stringToArray(str) {
    let day, month, year;
    if (str.includes('/')) {
        [month, day, year] = str.split('/').map(x => parseInt(x));
    } else if (str.includes('-')) {
        [day, month, year] = str.split('-').map(x => parseInt(x));
    }

    if (!year || isNaN(day) || isNaN(month) || isNaN(year)) {
        return null;
    }
    return [day, month, year];
}

function checkCorrectDate(array) {
    if (array === null) {
        return false;
    }

    const [day, month, year] = array

    const LONG_MONTH_ARRAY = [1, 3, 5, 7, 8, 10, 12];

    const isLeapYear = (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;

    // check month
    if (month < 1 || month > 12 || year <= 0) {
        return false;
    }

    // check day
    if (day < 1 || day > 31) {
        return false;
    }

    if (day === 31 && !LONG_MONTH_ARRAY.includes(month)) {
        return false;
    }

    // check February for correct day and leap year
    if (month === 2 && ((day === 29 && !isLeapYear) || day > 29)) {
        return false;
    }
    return true;
}

const res = getDates(inputDates, checkCorrectDate);
console.log(inputDates);
console.log(res);
```

2024-09-24 13:36 UTC, merged

2024-09-24 13:38 UTC, RatiboR1978 commented on 11-date-array/script.js
> +console.log(transformDates(arr));
и это написал такой же начинающий как я?

2024-09-24 14:10 UTC, GitEsense commented on 11-date-array/script.js
> +console.log(transformDates(arr));
> и это написал такой же начинающий как я?

Совершенно верно

2024-09-24 22:16 UTC, RatiboR1978 commented on 11-date-array/script.js
> +console.log(transformDates(arr));
мда, самооценка упала ниже плинтуса

2024-09-24 22:23 UTC, GitEsense commented on 11-date-array/script.js
> +console.log(transformDates(arr));
> мда, самооценка упала ниже плинтуса

Не стоит, ибо у каждого разный бекэнд и разный взгляд, не опускаем лапки и двигаемся дальше )